info:
  contact: {}
paths:
  /echo:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: echo example
      tags:
      - example
swagger: "2.0"
