info:
  contact: {}
paths:
  /test/echo:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: echo example
      tags:
      - example
  /user:
    get:
      description: Responds with the specific user.
      parameters:
      - description: The ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Get a user
      tags:
      - books
swagger: "2.0"
